### ISSUE TITLE
Configure CI and dev tools for this repository

### ISSUE THREAD

**Issue by hawkw** [sos-os/shelf#1]
- [ ] enable travis for this repository
- [ ] add rustfmt.toml
- [ ] add Travis config
- [ ] add Travis badge to README

**Comment by amanjeev** [comment]
I have not done Travis setup before but if you want I could take a shot at this, basically copying the stuff from ALARM etc.

**Comment by hawkw** [comment]
@amanjeev Go for it! Copying from ALARM is probably a good starting point; though there's some stuff in ALARM's Travis config that is only necessary because ALARM contains multiple crates.

I think I'll have to be the one actually turn Travis on for this repo.

**Comment by amanjeev** [comment]
Not sure about that but I asked for Travis CI app permissions for sos-os org. Please feel free to decline if this is something I should not have. No worries. 😄

**Comment by hawkw** [comment]
oh, no, that's great! I just wasn't sure if you'd be able to do that or not.

**Comment by amanjeev** [comment]
@hawkw thanks! without org permissions Travis cannot read the repos for me, in SOS-OS org. 

I guess I will just open a PR for you and maybe you can review it without me needing the permissions?

**Comment by amanjeev** [comment]
LOL! I am lost with chore vs feat :D

**Comment by hawkw** [comment]
@amanjeev here are some rules of thumb:
- if the commit adds or **changes documentation or tests*,* then it's `docs`/`test`
- if the commit **changes actual code**:
  + if the commit fixes an bug, then it's `fix`
  + if it adds new _user-facing functionality_  to the code, it's `feat`
     - if the project is an application/tool, "user facing functionality" would mean something that a user would see, if it's a library, then that would mean new/expanded APIs.
   + any other code changes are `style` or `refactor`
- **anything else** is `chore` except in special cases.

In general I'd say to only mark commits as `feat` if they actually change Rust source code, though there may be some cases where this rule doesn't apply (i.e. in the kernel, significant changes to the build process _might_ be enoughto add some features).

I hope that helps clear up the convention? Happy to keep discussing it if anything is still confusing.

**Comment by amanjeev** [comment]
@hawkw Thank you! This is very helpful indeed. I shall keep this algorithm close to me at all times. 🙇

**Comment by hawkw** [comment]
@amanjeev I've turned on Travis for this repo, btw. Right now I suspect the build will fail since there's nothing to build on master. :)

Glad that was useful --- i could make you a flowchart if it helps! :P

**Comment by amanjeev** [comment]
>  i could make you a flowchart if it helps! :P

I think _I_ should do that someday to solidify my understand (I know I am a little slow, lol). Or maybe a git hook that alerts me when I am about to commit a file with incorrect or missing proper keyword.

**Comment by hawkw** [comment]
@amanjeev you might want to check out [Commitizen](http://commitizen.github.io/cz-cli/), it's a CLI tool for writing commit messages using this convention. I haven't actually _used_ this, so I can't vouch for it, but you may find it useful!

**Comment by hawkw** [comment]
(Note also that the only reason I'm being a bit of a stickler for commit message style is that I intend to use them to automatically generate changelogs...)

**Comment by amanjeev** [comment]
> the only reason I'm being a bit of a stickler for commit message style 

Please forgive me; I think I wasn't clear. I am absolutely 110% with you about the commit message style and I appreciate that there is some concrete style to follow. In fact, I have started using this at work.:-)

I was merely apologizing about a series of amends above. I actually appreciate you pointing out if I have made a mistaken in any commit message. 

I will take a look at the https://commitizen.github.io/cz-cli/ tool. (thank you! :) )

**Comment by amanjeev** [comment]
Looks like I cannot add anything in Travis despite having permissions for the org. 😞 

<img width="349" alt="screen shot 2018-02-04 at 2 53 11 pm" src="https://user-images.githubusercontent.com/160476/35781684-472284ea-09bb-11e8-9ccd-8b9209813f5c.png">

**Comment by hawkw** [comment]
@amanjeev huh, that's weird, I thought you had that permission --- maybe it's only on the GitHub side, and I have to do something else to grant permission on Travis? Regardless, I turned builds on for this repo, so it should work now.
